CREATE TABLE IF NOT EXISTS t (v INT NOT NULL);
INSERT INTO t (v) VALUES (1);
INSERT INTO t (v) VALUES (2);
INSERT INTO t (v) VALUES (3);
INSERT INTO t (v) VALUES (4);
INSERT INTO t (v) VALUES (5);
INSERT INTO t (v) VALUES (6);
